from django.urls import path
from .views import (
    ResumeAnalysisView, JobMatchView, CandidateRankingView,
    AIQuestionGeneratorView, AIQuestionDetailView, RecruiterAIStatsView,
    TalentPoolView, TalentPoolDetailView,
    NotificationView, NotificationMarkReadView,
    OfferResponseView, ActivityLogView, AuditLogView,
    HiringFunnelView, ChatHistoryView, AIChatView,
    VoiceInterviewView, VoiceInterviewDetailView,
    ExportView, CompanyPublicView, RecruiterAssistantView,
    CareerGuidanceView, CoverLetterView, ResumeTailoringView,
    ProfileCompletionView, HiringInsightsView, CareerTwinView,
    SkillGapView, MockInterviewView,
)

urlpatterns = [
    path('resume-analysis/', ResumeAnalysisView.as_view(), name='resume-analysis'),
    path('job-match/<int:job_id>/', JobMatchView.as_view(), name='job-match'),
    path('rankings/<int:job_id>/', CandidateRankingView.as_view(), name='candidate-rankings'),
    path('questions/', AIQuestionGeneratorView.as_view(), name='ai-questions'),
    path('questions/<int:pk>/', AIQuestionDetailView.as_view(), name='ai-question-detail'),
    path('stats/', RecruiterAIStatsView.as_view(), name='ai-stats'),
    path('talent-pool/', TalentPoolView.as_view(), name='talent-pool'),
    path('talent-pool/<int:pk>/', TalentPoolDetailView.as_view(), name='talent-pool-detail'),
    path('notifications/', NotificationView.as_view(), name='notifications'),
    path('notifications/<int:pk>/read/', NotificationMarkReadView.as_view(), name='notification-read'),
    path('notifications/mark-all-read/', NotificationMarkReadView.as_view(), name='notifications-mark-all'),
    path('offer-response/<int:decision_id>/', OfferResponseView.as_view(), name='offer-response'),
    path('activity-log/', ActivityLogView.as_view(), name='activity-log'),
    path('audit-log/', AuditLogView.as_view(), name='audit-log'),
    path('hiring-funnel/', HiringFunnelView.as_view(), name='hiring-funnel'),
    path('chat/', ChatHistoryView.as_view(), name='chat-history'),
    path('chat/send/', AIChatView.as_view(), name='ai-chat'),
    path('voice-interview/', VoiceInterviewView.as_view(), name='voice-interview'),
    path('voice-interview/<int:pk>/', VoiceInterviewDetailView.as_view(), name='voice-interview-detail'),
    path('export/', ExportView.as_view(), name='export'),
    path('company/', CompanyPublicView.as_view(), name='company-public'),
    path('recruiter-assistant/', RecruiterAssistantView.as_view(), name='recruiter-assistant'),
    path('career-guidance/', CareerGuidanceView.as_view(), name='career-guidance'),
    path('cover-letter/', CoverLetterView.as_view(), name='cover-letter'),
    path('resume-tailoring/', ResumeTailoringView.as_view(), name='resume-tailoring'),
    path('profile-completion/', ProfileCompletionView.as_view(), name='profile-completion'),
    path('hiring-insights/', HiringInsightsView.as_view(), name='hiring-insights'),
    path('career-twin/', CareerTwinView.as_view(), name='career-twin'),
    path('skill-gap/', SkillGapView.as_view(), name='skill-gap'),
    path('mock-interview/', MockInterviewView.as_view(), name='mock-interview'),
]
